[package]
name = "libglimra"
version = "2.0.1"
authors = []
edition = "2021"

[lib]
name = "libglimra"
path = "src/libglimra.rs"
crate-type = ["cdylib"]

[dependencies]
lazy_static = "1.5.0"
once_cell = "1.19.0"
rustler = "0.34.0"
tree-sitter = "0.22.6"
tree-sitter-bash = "0.21.0"
tree-sitter-c = "0.21.4"
tree-sitter-css = "0.21.1"
tree-sitter-elixir = "0.2.0"
tree-sitter-erlang = "0.7.0"
tree-sitter-gleam = { git = "https://github.com/gleam-lang/tree-sitter-gleam", rev = "426e67087fd62be5f4533581b5916b2cf010fb5b" }
tree-sitter-go = "0.21.2"
tree-sitter-highlight = "0.22.6"
tree-sitter-html = "0.20.4"
tree-sitter-javascript = "0.21.4"
tree-sitter-json = "0.21.0"
tree-sitter-python = "0.21.0"
tree-sitter-rust = "0.21.2"
